require 'sytec.plugins.mason'
require 'sytec.plugins.lspconfig'
require 'sytec.plugins.lspsaga'
require 'sytec.plugins.null-ls'
require 'sytec.plugins.lsp-colors'
require 'sytec.plugins.autopairs'
require 'sytec.plugins.cmp'
require 'sytec.plugins.colorizer'
require 'sytec.plugins.comment'
-- require 'sytec.plugins.copilot'
require 'sytec.plugins.gitsigns'
require 'sytec.plugins.harpoon'
require 'sytec.plugins.hop'
require 'sytec.plugins.indentmini'
require 'sytec.plugins.lualine'
require 'sytec.plugins.telescope'
-- require 'sytec.plugins.tokyonight'
-- require 'sytec.plugins.kanagawa'
require 'sytec.plugins.gruvbox'
-- require 'sytec.plugins.catppuccin'
require 'sytec.plugins.treesitter-textobjects'
require 'sytec.plugins.treesitter'
require 'sytec.plugins.ts-autotag'
require 'sytec.plugins.web-devicons'
require 'sytec.plugins.zen'
